# Beginning of Dockerfile-pre
FROM debian:latest

RUN apt-get -yy update && apt-get -yy dist-upgrade && apt-get -yy autoremove && apt-get -yy autoclean
# Packages needed for basic init scripts
RUN apt-get -yy install \
    apt-transport-https \
    git \
    sudo \
    openssh-server

RUN mkdir -p /init-scripts/
RUN mkdir -p /install-scripts/
# End of Dockerfile-pre
