FROM debian:latest

RUN apt-get -yy update && apt-get -yy dist-upgrade && apt-get -yy autoremove && apt-get -yy autoclean
RUN apt-get -yy install \
    vim \
    nload \
    net-tools \
    dnsutils \
    htop \
    git \
    build-essential \
    gdb \
    curl \
    wget \
    tar \
    gzip \
    tmux \
    sysstat \
    netcat \
    iperf3 \
    nmap \
    openssh-server

RUN mkdir -p /init-scripts/
ADD scripts/*.sh /init-scripts/
ADD .env setenv.sh /init-scripts/

