version: "3"

services:
  debian:
    restart: unless-stopped
    build:
      context: .
      dockerfile: debian/debian.Dockerfile
    ports:
      - "${SERVICE_HOST:-127.0.0.1}:11022:22"
    environment:
      - SERVICE_HOST
      - USER_NAME=${USER_NAME:-leeopop}
    volumes:
      - debian-workspace:/workspace
  dpdk:
    restart: unless-stopped
    build:
      context: .
      dockerfile: dpdk/dpdk.Dockerfile
    ports:
      - "${SERVICE_HOST:-127.0.0.1}:12022:22"
    environment:
      - SERVICE_HOST
      - USER_NAME=${USER_NAME:-leeopop}
    volumes:
      - dpdk-workspace:/workspace
  node:
    restart: unless-stopped
    build:
      context: .
      dockerfile: node/node.Dockerfile
    ports:
      - "${SERVICE_HOST:-127.0.0.1}:13022:22"
    environment:
      - SERVICE_HOST
    volumes:
      - node-workspace:/workspace
volumes:
  debian-workspace:
  dpdk-workspace:
  node-workspace:
