version: "3"

services:
  debian:
    cap_add:
      - AUDIT_WRITE
      - AUDIT_CONTROL
    restart: unless-stopped
    build:
      context: .
      dockerfile: debian/Dockerfile
    ports:
      - "${SERVICE_HOST:-127.0.0.1}:12022:22"
    environment:
      - SERVICE_HOST
      - USER_NAME=${USER_NAME:-leeopop}
    volumes:
      - workspace:/workspace
  node:
    cap_add:
      - AUDIT_WRITE
      - AUDIT_CONTROL
    restart: unless-stopped
    build:
      context: .
      dockerfile: node/Dockerfile
    ports:
      - "${SERVICE_HOST:-127.0.0.1}:12023:22"
    environment:
      - SERVICE_HOST
    volumes:
      - workspace:/workspace
  rust:
    cap_add:
      - AUDIT_WRITE
      - AUDIT_CONTROL
    restart: unless-stopped
    build:
      context: .
      dockerfile: rust/Dockerfile
    ports:
      - "${SERVICE_HOST:-127.0.0.1}:12024:22"
    environment:
      - SERVICE_HOST
      - USER_NAME=${USER_NAME:-leeopop}
    volumes:
      - workspace:/workspace
  dpdk:
    cap_add:
      - AUDIT_WRITE
      - AUDIT_CONTROL
    restart: unless-stopped
    build:
      context: .
      dockerfile: dpdk/Dockerfile
    ports:
      - "${SERVICE_HOST:-127.0.0.1}:12025:22"
    environment:
      - SERVICE_HOST
      - USER_NAME=${USER_NAME:-leeopop}
    volumes:
      - workspace:/workspace
  python:
    cap_add:
      - AUDIT_WRITE
      - AUDIT_CONTROL
    restart: unless-stopped
    build:
      context: .
      dockerfile: python/Dockerfile
    ports:
      - "${SERVICE_HOST:-127.0.0.1}:12026:22"
    environment:
      - SERVICE_HOST
      - USER_NAME=${USER_NAME:-leeopop}
    volumes:
      - workspace:/workspace
volumes:
  workspace:
