# Beginning of dpdk install
RUN apt-get install -y linux-headers-amd64
RUN apt-get install -y build-essential libnuma-dev git meson python3-pyelftools
RUN apt-get install -y curl
RUN apt-get install -y libclang-dev clang llvm-dev

RUN git clone -b v20.11 "http://dpdk.org/git/dpdk" /dpdk

WORKDIR /dpdk

RUN meson build
RUN ninja -C build
RUN ninja -C build install
RUN ldconfig

WORKDIR /
RUN rm -rf /dpdk
# End of dpdk install

