RUN apt-get -yy install \
    vim \
    nload \
    net-tools \
    dnsutils \
    htop \
    build-essential \
    cmake \
    autoconf \
    gdb \
    curl \
    wget \
    tar \
    gzip \
    unzip \
    tmux \
    sysstat \
    iperf3 \
    nmap \
    man \
    whois
